const ChecklistActionsTypes = {
  FETCH_CHEKCLIST_START: 'FETCH_CHECKLIST_START',
  FETCH_CHEKCLIST_SUCCESS: 'FETCH_CHECKLIST_SUCCESS',
  FETCH_CHEKCLIST_FAIL: 'FETCH_CHECKLIST_FAIL',
  
  POST_CHEKCLIST_START: 'POST_CHECKLIST_START',
  POST_CHEKCLIST_SUCCESS: 'POST_CHECKLIST_SUCCESS',
  POST_CHEKCLIST_FAIL: 'POST_CHECKLIST_FAIL',

  DELETE_CHEKCLIST_START: 'DELETE_CHECKLIST_START',
  DELETE_CHEKCLIST_SUCCESS: 'DELETE_CHECKLIST_SUCCESS',
  DELETE_CHEKCLIST_FAIL: 'DELETE_CHECKLIST_FAIL',
};

export default ChecklistActionsTypes;